### ISSUE TITLE
500 when trying to clear results

### ISSUE THREAD

**Issue by jimbobday** [zpurcey/new-teamtemp#17]
![click here](https://cloud.githubusercontent.com/assets/25065819/21865992/31ce21d4-d8ad-11e6-9714-0a9b873930f5.PNG)

Pre-requites
* Have two teams setup under a single login
* Have results in for those two teams

Steps to reproduce
1. Login in teamtemp app https://teamtempapp.herokuapp.com/admin/pDQujttH
2. Scroll down to the bottom of the page and click on "Click here to clear all current results"

Expected outcome
1. All current results are cleared and the page reloads

Actual results
1. Page loads https://teamtempapp.herokuapp.com/reset/pDQujttH with "Server Error (500)" displayed

**Comment by rloomans** [comment]
FYI, the version of code that is deployed to https://teamtempapp.herokuapp.com/ is my fork (https://github.com/rloomans/new-teamtemp)

I've plugged that bug, and archived the survey. Let me know if you have any other issues.

(Nice bug report, BTW :smile:)

**Comment by jimbobday** [comment]
Thanks, working as expected now.

Bought me back to my days in QA many years ago :smile:
