### ISSUE TITLE
Feature request - Remove words from a team temperature submission

### ISSUE THREAD

**Issue by erae** [zpurcey/new-teamtemp#4]
Feature request - Remove words from a team temperature submission. The reason for this is that if an inappropriate word is submitted it would be nice to be able to remove it so that it doesn't appear on the BVC pages.

**Comment by zpurcey** [comment]
We've managed this in the past by addressing the team and asking the individual to revise their submission.  Users can edit their own words.  Admin ability to edit words could lead to inappropriate manipulation of results.

Perhaps replacing censored words with the word 'censored' would allow transparency that an admin action occurred.

Could be added as an additional feature/hack to the settings page fairly easily if was a search and replace for a given string.

**Comment by zpurcey** [comment]
You can find the delete word function on the settings page All Teams -> Admin -> settings url hidden at the bottom of the page.
