### ISSUE TITLE
Word Cloud through mashape stopped working

### ISSUE THREAD

**Issue by zpurcey** [zpurcey/new-teamtemp#5]
The word cloud api provider has ended their service without notice causing BVC to render without word cloud.

**Comment by zpurcey** [comment]
I've been working a replacement service. Got most of it working as a drop in replacement for the mashape service.

Please ping me if you are actively using the current teamtempapp.herokuapp.com instance to +1 the effort so I know the urgency.

Andrew.

**Comment by travisjwarren** [comment]
Thanks @zpurcey , had a few teams asking what's happened.  I just haven't had a chance to look.

If you can get your fix completed in the next few days that would be great.

**Comment by mvillis** [comment]
Happy to assist with testing/review @zpurcey

**Comment by zpurcey** [comment]
Hey Travis and Mike!
I've checked in the code change.  I'll hold off pushing it to heroku till I hear back. The biggest risk is probably just screwing up an environment variable running the deployment script. Its been a while :)

I've been able to test using current data backed up from Heroku on my local machine.

Andrew.

**Comment by zpurcey** [comment]
Change complete, Heroku updated. Marking this closed.

**Comment by mvillis** [comment]
Nice work @zpurcey.

Works like a charm!
