### ISSUE TITLE
Word Cloud Capitalisation

### ISSUE THREAD

**Issue by cwilso15** [zpurcey/new-teamtemp#7]
Hi All, small suggestion: is there a chance we could force lower casing the words in the word cloud so that mismatched capitals still count together to grow the size of the word? Noticed this morning in my team's results that there’s 'Tired' and 'tired' both as separate words. Ooops, I meant 'Awesome' and 'awesome'.... ;-)

Many thx in advance, Craig W.

**Comment by zpurcey** [comment]
Hi Craig,

Yes absolutely. I actually flipped it off as my initial implementation was lower case.

@travisjwarren @mvillis you guys agree go with lower case all words for the word cloud?  We trade off the Camel Case sentence readability a touch but get better frequency matching.

Cheers!

**Comment by travisjwarren** [comment]
Fine by me.

**Comment by cwilso15** [comment]
Thanks All!

Sent from my iPhone

On 8 May 2015, at 14:29, Travis Warren <notifications@github.com<mailto:notifications@github.com>> wrote:

Fine by me.

On Friday, May 8, 2015, zpurcey <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hi Craig,
>
> Yes absolutely. I actually flipped it off as my initial implementation was
> lower case.
>
> @travisjwarren <https://github.com/travisjwarren> @mvillis
> <https://github.com/mvillis> you guys agree go with lower case all words
> for the word cloud? We trade off the Camel Case sentence readability a
> touch but get better frequency matching.
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zpurcey/new-teamtemp/issues/7#issuecomment-100083954>.
>

—
Reply to this email directly or view it on GitHub<https://github.com/zpurcey/new-teamtemp/issues/7#issuecomment-100097897>.

________________________________

This e-mail is sent by Suncorp Group Limited ABN 66 145 290 124 or one of its related entities "Suncorp".
Suncorp may be contacted at Level 28, 266 George Street, Brisbane or on 13 11 55 or at suncorp.com.au.
The content of this e-mail is the view of the sender or stated author and does not necessarily reflect the view of Suncorp. The content, including attachments, is a confidential communication between Suncorp and the intended recipient. If you are not the intended recipient, any use, interference with, disclosure or copying of this e-mail, including attachments, is unauthorised and expressly prohibited. If you have received this e-mail in error please contact the sender immediately and delete the e-mail and any attachments from your system.
